### ISSUE TITLE
Week 1 Grading

### ISSUE THREAD

**Issue by crystalwidjaja** [florayuan18/pikachudrinkingwindex#10]
Issues for the Week:
[Technicals](https://github.com/florayuan18/pikachudrinkingwindex/issues/29)
[Giving Assignments & Backlog](https://github.com/florayuan18/pikachudrinkingwindex/issues/30)
[Design Guide on Wiki](https://github.com/florayuan18/pikachudrinkingwindex/issues/28)
[Deployment Guide on Wiki](https://github.com/florayuan18/pikachudrinkingwindex/issues/9)
[Github Policy Document on Wiki](https://github.com/florayuan18/pikachudrinkingwindex/issues/8)

**Comment by crystalwidjaja** [comment]
- [ ] [Design](url)
- [ ] Technicals (All technicals in [scrum board](https://github.com/florayuan18/pikachudrinkingwindex/projects/1) To Do)
1.  Video Game api
2. Database for “Collection” feature (games you saved for later)
3. Search function
4. Video game library
5. Filter by genre etc.
6. Video game description when title clicked
7. Log in?
8. Nav bar
9. Community spotlight?
10. Javascript page transitions (fading in and out)
11. Scrolling down - appears / scroll transitions - https://scrollrevealjs.org/api/reveal.html
12. Cards on the search page & my collection page
13. Option to add a game from the search page to “my collection”
- [ ] [Github](url)
- [ ] [Deployment](https://github.com/florayuan18/pikachudrinkingwindex/wiki/Deployment-Guide)
- [ ] [Scrum Board](https://github.com/florayuan18/pikachudrinkingwindex/projects/1)

**Comment by purplebears321** [comment]
Scrum Board (Crystal): 1/1 Good design plan. The page was easily navigable and the assignees how they are constantly collaborating,. They also showed good organization with who creates tickets and what aspects of the project each person is working on.

**Comment by TMarwah** [comment]
Github Manager (Flora) 1/1 - Wiki fully outlines project contribution guidelines and highlights forking/branching/pulling processes clearly.

**Comment by zenxha** [comment]
**UI and Design** (Kira)1/1
- Wiki has full outline of deployment design, and github. Easy access to wireframe google sides, which looked pretty clean. Brainwrite easy to access on the wiki page

**Comment by ncrxue** [comment]
Technical Officer (Calvin): 1/1 
- Project plans are logical and feasible, 13 ideas (going above and beyond the 10 required), working on search bar function, looks good.

**Comment by LordRoop** [comment]
Deployment Officer (Maggie) 

- Deployment guide is clear and neat. It contains all important Info at the top of the page where it is easy to find.

**Comment by jm1021** [comment]
Piachu Drinking Windex - Calvin 4.9/5
* Nicely laid out Design 1/1
* Technical OK, action to move this to somewhere prominent .9/1
* Adding Branches, well thought out doc 1/1
* Nice deployment guide, quick update guide 1/1
* Active scrum board with top 10-12 1/1
