### ISSUE TITLE
Running Website, Updates

### ISSUE THREAD

**Issue by florayuan18** [florayuan18/pikachudrinkingwindex#39]
- [ ] show the web site running from URL (https)
- [ ] demonstrate being able to perform an update

**Comment by maggie3000** [comment]
Deployment Wiki: https://github.com/florayuan18/pikachudrinkingwindex/wiki/Deployment-Guide

(added an update section)

**Comment by maggie3000** [comment]
https://github.com/florayuan18/pikachudrinkingwindex/wiki/Deployment-Guide#update-deployment
