### ISSUE TITLE
Week 8 Crossover Grading - Maggie

### ISSUE THREAD

**Issue by maggie3000** [florayuan18/pikachudrinkingwindex#55]
# Crossover Review
Crossover Grader: Rachel Lee
### Tangibles
[Review Video](https://www.loom.com/share/d934aeeacdc845caa0d4477ba338041b)
[FRQ Guide on Wiki](https://github.com/florayuan18/pikachudrinkingwindex/wiki/Maggie-FRQ-Guide)
[Runtime Link](http://umbrellabox.cf/AboutUs/aboutmaggie)

**Notes for reviewer**
- all FRQs show output on my individual webpage (except for MaggieForLoop.java)
- most FRQs have input
- MaggieForLoop.java runs on console in intelliJ

**Comment by rachelklee** [comment]
Crossover Grading
Grading For: Maggie
Graded By: Rachel

[Review Video]()
Total Score:
| FRQ | Evaluation | Score |
| --- | --- | --- |
| Unit 2 | | |
| Unit 3 | | |
| Unit 4 | | |
| Unit 5 | | |
| Unit 6 | | |
| Unit 7 | | |
| Unit 8 | | |
| Unit 9 | | |
All Tangibles
Jekyll/Github Pages
Design
