### ISSUE TITLE
Week 8 Crossover Grading - Flora

### ISSUE THREAD

**Issue by florayuan18** [florayuan18/pikachudrinkingwindex#56]
| FRQ            | Github Page   | Replit  |
| ------------------- | ----------------- | ----------------- | 
| Unit 2 - Light Sequence | [Reflection ](http://blog.umbrellabox.cf/florafrq/) | [Light Sequence](https://replit.com/@florayuan18/FloraFRQ#LightSequence.java)|
| Unit 3 - Dinner RSVP | [Reflection ](http://blog.umbrellabox.cf/florafrq/) | [Dinner RSVP](https://replit.com/@florayuan18/FloraFRQ#DinnerRSVP.java) |
| Unit 4 -  Coin Game | [Reflection ](http://blog.umbrellabox.cf/florafrq/) | [Coin Game](https://replit.com/@florayuan18/FloraFRQ#CoinGame.java) |
| Unit 4 -  Hack | [Reflection ](http://blog.umbrellabox.cf/florafrq/) | [Hack ](https://replit.com/@florayuan18/FloraFRQ#Hack.java) | 
| Unit 5 -  Invitation | [Reflection ](http://blog.umbrellabox.cf/florafrq/) | [Invitation ](https://replit.com/@florayuan18/FloraFRQ#Invitation.java) | 
| Unit 5 - Password Generator | [Reflection](http://blog.umbrellabox.cf/florafrq/) | [Password Generator](https://replit.com/@florayuan18/FloraFRQ#PasswordGenerator.java)|
| Unit 6 - Payroll | [Reflection](http://blog.umbrellabox.cf/florafrq/) | [Payroll ](https://replit.com/@florayuan18/FloraFRQ#Payroll.java)| 
| Unit 7 -  Username | [Reflection](http://blog.umbrellabox.cf/florafrq/) | [Username ](https://replit.com/@florayuan18/FloraFRQ#Username.java)| 
| Unit 8 -  Experimental Farm | [Reflection](http://blog.umbrellabox.cf/florafrq/) | [Experimental Farm ](https://replit.com/@florayuan18/FloraFRQ#ExperimentalFarm.java), [Plot](https://replit.com/@florayuan18/FloraFRQ#Plot.java), [Plot Main](https://replit.com/@florayuan18/FloraFRQ#PlotMain.java) |
| Unit 9 -  Books | [Reflection](http://blog.umbrellabox.cf/florafrq/) | [Unit8Animal](https://replit.com/@florayuan18/FloraFRQ#Unit9Book.java), [Book](https://replit.com/@florayuan18/FloraFRQ#Book.java), [BookListing ](https://replit.com/@florayuan18/FloraFRQ#BookListing.java)| 
| Unit 9 -  Animals | [Reflection](http://blog.umbrellabox.cf/florafrq/) | [Unit9Animal](https://replit.com/@florayuan18/FloraFRQ#Unit9Animal.java), [Animal](https://replit.com/@florayuan18/FloraFRQ#Animal.java), [Elephant ](https://replit.com/@florayuan18/FloraFRQ#Elephant.java) | 
| Unit 10 -  Number System | [Reflection ](http://blog.umbrellabox.cf/florafrq/) | [Number System](https://replit.com/@florayuan18/FloraFRQ#NumberSystem.java)|

[Main Function](https://replit.com/@florayuan18/FloraFRQ#Main.java)
[My Reflection on Allen's Code](https://github.com/zenxha/m22-2-social-credit-farmers/issues/31)
[Video](https://youtu.be/DoWjAewU8Pk)

**Comment by purplebears321** [comment]
## Allen Reflection

#### Comparison
- FRQ 4 Comparison
>- Flora used static and private variables which helped minimize repetitive code
>- Rather than using an imported class, she used the random function to randomize the integer values
- FRQ 3 Comparison
>- Flora used if statements for each value selected, I used an array list that used the number inputted to find the element on the array, was a bit more efficient
>-  For her string comparison, she returned booleans since it was terminal based, while I converted to a string to produce an output
- FRQ 5 Comparison
>- Both used multiple classes to implement the feature
>- Flora's was a bit more optimized for the terminal while ours was more optimal for the MVC approach

#### Summary
- With the FRQs I was able to develop a much better understanding of how the information gets processed through the controller onto the html template
- The FRQs also gave me much practice with variable conversions, as much of the input and output must differ as it goes through the algorithms (string to boolean, integer to string, etc)
- I was able to develop more knowledge on how arrays work, especially with using the split function to create new strings, and add elements with array lists
>- However, I am still a little rough around the edges with 2d arrays, will likely be where I focus my later learnings on
-

**Comment by purplebears321** [comment]
|Feature|Evaluation|Score|
|:----:|:----:|:----:|
|Github/Wiki page|Flora has a [reflection](http://blog.umbrellabox.cf/florafrq/) on her jekyll page that breakdowns the individual FRQs and her takeaways from each, reading them showed me that she developed a growing skill in each aspect and is truly learning more about Java|3/3|
|FRQ Menu|Flora has her reflections and FRQs linked easily on her [review ticket](https://github.com/florayuan18/pikachudrinkingwindex/issues/56), has links to her repl FRQs which are easy to access and in a single menu so no complex navigation is required|3/3|
|Github Source|The links on the [ticket](https://github.com/florayuan18/pikachudrinkingwindex/issues/56) direct to the code sources on her replit|3/3|
|2 Inputs|Has her input done well on [Unit 4 Hack FRQ](https://replit.com/@florayuan18/FloraFRQ#Hack.java) and on her [Unit 3 Dinner FRQ](https://replit.com/@florayuan18/FloraFRQ#DinnerRSVP.java), but both were done inside repl.it and not through MVC on the main PBL website|0.8/1|

### Total Score: 9.8/10

**Comment by purplebears321** [comment]
## Allen Reflection

#### Comparison
- FRQ 4 Comparison
>- Flora used static and private variables which helped minimize repetitive code
>- Rather than using an imported class, she used the random function to randomize the integer values
- FRQ 3 Comparison
>- Flora used if statements for each value selected, I used an array list that used the number inputted to find the element on the array, was a bit more efficient
>-  For her string comparison, she returned booleans since it was terminal based, while I converted to a string to produce an output
- FRQ 5 Comparison
>- Both used multiple classes to implement the feature
>- Flora's was a bit more optimized for the terminal while ours was more optimal for the MVC approach

#### Summary
- With the FRQs I was able to develop a much better understanding of how the information gets processed through the controller onto the html template
- The FRQs also gave me much practice with variable conversions, as much of the input and output must differ as it goes through the algorithms (string to boolean, integer to string, etc)
- I was able to develop more knowledge on how arrays work, especially with using the split function to create new strings, and add elements with array lists
>- However, I am still a little rough around the edges with 2d arrays, will likely be where I focus my later learnings on
- Another weakness I have is with handling multiple classes. I can sometimes get lost and mess up my formatting, which can lead me to spending much too time bug fixing my code

**Comment by florayuan18** [comment]
Flora Reflection:

**Comparison**
- FRQ 10 Comparison
>- Allen used Parse Int which found the string and turned it into an integer so that he could compare the values
>- He put his code on MVC instead of Replit.  His use of javascript makes for a nicer display.

- FRQ 3 Comparison
>- Allen used an array list to find an element in an array, which was more efficient than my use of many if statements
>- Allen converted the boolean back into a string to display it properly on the website, while I just left mine as booleans.

- FRQ 7 Comparison
>- Allen requested the parameters so he used those as the variables instead of actually establishing them.
>- Allen is also displaying the good through javascript and he is passing the results with Thymeleaf, so the end of our codes look different to accommodate our different platforms.

**Summary**
- Overall, doing the FRQs really helped me solidify the overall structure of the code, as well as when to use what when accomplishing certain tasks.
- Doing the Unit 9 FRQs specifically really helped me understand the implementation of superclasses and subclasses, as well as how to use the super keyword to my advantage.
- I also learned a lot about using loops in different contexts to satisfy the different requirements.
- I still need to work on using both 1D and 2D arrays, specifically with skills like traversing and extracting information.  I find the format difficult to understand and confusing to read, so I need to focus on these more.
- I also need to work on working with multiple different files and organizing information between both.  I often found myself repeating the same code in different files because I didn't plan well enough.
