### ISSUE TITLE
Week 8 Crossover Grading - Crystal

### ISSUE THREAD

**Issue by crystalwidjaja** [florayuan18/pikachudrinkingwindex#60]
- [ ] At least 2 inputs for FRQs
- [ ] FRQ 2
- [ ] FRQ 3
- [ ] FRQ 4
- [ ] FRQ 5
- [ ] FRQ 6
- [ ] FRQ 7
- [ ] FRQ 8
- [ ] FRQ 9
- [ ] FRQ 10

**Comment by crystalwidjaja** [comment]
- [ ] At least 2 inputs for FRQs
- [ ] FRQ 2
- [ ] FRQ 3
- [ ] FRQ 4
- [ ] FRQ 5
- [ ] FRQ 6
- [ ] FRQ 7
- [ ] FRQ 8
- [ ] FRQ 9
- [ ] FRQ 10

**Comment by TMarwah** [comment]
|Feature|Evaluation|Score|
|:----:|:----:|:----:|
|Github/Wiki page|Crystal has a clear [FRQ Guide + Reflections](https://github.com/florayuan18/pikachudrinkingwindex/wiki/Crystal-FRQ-Guide).  She made the purpose of each FRQ very clear as well as the concept that should be learned from them. The integrated reflections along with direct code references make it very easy to understand each FRQ and its key takeaways. |3/3|
|FRQ Menu| The FRQs are very well organized on a single webpage, making it easy to navigate between them without clicking through numerous menus. One thing I would suggest is some CSS/Bootstrap formatting to make the page more aesthetically pleasing and a little less cluttered. Also, some of the FRQs are not online, but having the java on your page is still nice | 2.5/3|
|Github Source| The code is easily accessible on the [FRQ Guide](https://github.com/florayuan18/pikachudrinkingwindex/wiki/Crystal-FRQ-Guide) making it very convenient to view the direct source code. |3/3|
|2 Inputs| Crystal has gone above the expected 2 inputs and has inputs for FRQs 2-5. |1/1|

### Total Score: 9.5/10
