### ISSUE TITLE
Week 8 Crossover Grading - Calvin

### ISSUE THREAD

**Issue by QwikSP** [florayuan18/pikachudrinkingwindex#61]
[run time](https://replit.com/@Qwiks/CB-FRQs#Main.java)

**Comment by Uhpachee** [comment]
Kian's Score: 9/10
FRQs (repl.it): [Link](https://replit.com/@KianKishimoto/FRQs-Trimester-2#Main.java)

**Comment by QwikSP** [comment]
[run time](https://replit.com/@Qwiks/CB-FRQs#Main.java)
